name: GOAT Compile

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "obteniendo ultima version del codigo"
        uses: actions/checkout@v3
      
      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilation"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target