name: GOAT Compile

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Obteniendo la última versión del código"
        uses: actions/checkout@v3
      
      - name: "Instalando Java"
        uses: actions/setup-java@v2
        with:
          java-version: 17
      
      - name: "Compilación"
        run: ./mvnw clean install

      - name: "Verificando el paquete"
        run: ls -ltra target

  depchecktest:
    runs-on: ubuntu-latest
    name: Depcheck Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Instalando Java"
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: "Compilación"
        run: ./mvnw clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: "Subir resultados de la prueba"
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports


