name: GOAT Compile

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Obtener codigo"
        uses: actions/checkout@v3

      - name: "Instalar Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target

      - name: "Dependency Check"
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'WebGoat'
          path: '.'
          format: 'XML'
          out: 'reports'

      - name: "Verificar reporte"
        run: ls -ltra reports

      - name: "Generacion de imagen"
        run: |
          docker build -t mario-repositorio .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Trivy report
        run: |
         trivy image -f json -o mariorepositorio.json  mario-repositorio

      - name: "Cargar reportes automatizados"
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python3 upload-report.py -f ${{github.workspace}}/reports/dependency-check-report.xml -t "Dependency Check Scan" -l "$API_KEY"
          python3 upload-report.py -f mariorepositorio.json -t "Trivy Scan" -l "$API_KEY"
