name: GOAT

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pase de construcción"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fase de pruebas"
 
  qa:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fase de QA"

  prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fase de producción"
